import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const animalHunter= localFont({
src:'../public/fonts/AnimalHunterRegular.woff2',
variable:'--font-animal-hunter',
weight:'400',
style:'normal'
})

const mesoninaRegular= localFont({
src:'../public/fonts/Mesonina-Regular.woff2',
variable:'--font-mesonina-regular',
weight:'400',
style:'normal'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${animalHunter.variable} ${mesoninaRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
